### ISSUE TITLE
🎨Cadastro de Usuário

### ISSUE THREAD

**Issue by diegoemygdio** [adtecnologia/smartmenu.adsolucoestecnologia.com.br#4]
<h1> 🎯 Tela para Cadastrar Usuários. </h1>

<h2> 📷 Campos Usuários de Acordo com a Modelagem</h2>

![image](https://user-images.githubusercontent.com/77404306/147135448-9db1f0f8-9a9a-40a9-9e10-e763e03587f7.png)

<h2> ✔️ Funcionalidades</h2>

- [x] Cadastro Resumido

> Cadastrar apenas os dados da Tabela Usuário

<hr/>

- [x] Cadastro Completo

> Cadastrar os dados da Tabela de Cliente

<hr/>

- [x] Dividir os campos em abas para facilitar o preenchimento

📷 Exemplo de Tela

![image](https://user-images.githubusercontent.com/77404306/147136407-29f3f4fb-cee7-4639-88c4-982aa5d42759.png)

**Comment by nattyFS** [comment]
![image](https://user-images.githubusercontent.com/61321090/147975100-c280ac59-8166-4748-9186-141d50b2d6e1.png)




eu vou melhorar a aparencia hahahahha, só pra mostrar que já está funcionando

**Comment by nattyFS** [comment]
Aliás eu já tirei o rodapé com o bootstrap, tá só smart-menu e tals

**Comment by nattyFS** [comment]
Vou fazendo as outras tabelas e depois vou estilizar tudo bonitinho

**Comment by nattyFS** [comment]
acredito que assim vá mais rápido
