### ISSUE TITLE
⚙️Cadastro de Usuário

### ISSUE THREAD

**Issue by diegoemygdio** [adtecnologia/smartmenu.adsolucoestecnologia.com.br#6]
<h1> 🎯 Gerar o WS e estrutura no Banco de Dados para cadastrar os usuários de acordo com seu Tipo.</h1>

<h2> ✔️ Tipos de Usuários </h2>

- [x] Usuário

> Tem cadastro no site de forma incompleta, ou seja, não pode realizar a assinatura de planos.
<hr/>

- [x] Cliente

> Tem cadastro completo no site, podendo, realizar a assinatura de planos.
<hr/>

- [x] Admin

> Cadastrado pelo Dev.

**Comment by nattyFS** [comment]
Aqui eu posso criar uma tabela só para tipos de usuario?

**Comment by diegoemygdio** [comment]
Pode.
